server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: 192.168.175.129:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.175.129
    virtual-host: /qiangge
    username: dzq951228
    password: dzq951228
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
  thymeleaf:
    cache: false


feign:
  sentinel:
    enabled: true
  httpclient:
    connection-timeout: 600000

